### ISSUE TITLE
Litecoin to Bitcoin Lightning swap error

### ISSUE THREAD

**Issue by ecurrencyhodler** [submarineswaps/swaps-service#102]
When I select Litecoin there is a console error.  When I paste in a 100 satoshi invoice, the error shows "UnexpectedNetworkSelected".

**Comment by alexbosworth** [comment]
Can you share the payment request?

**Comment by alexbosworth** [comment]
I think I replicated the issue and it should be fixed now

**Comment by ecurrencyhodler** [comment]
`lnbc1u1pwxmwwspp5v7vdnza28q6sejd0ejjc692t7n8u5savacstv3j76gmm70dvn6vsdqqcqzys4htgmffauhg489cxtt5kswwfvh6sflhvneyu9uf2hhhnpguy7hp5xefuqmmxgav5mj3ak84jllrkn02kdn9fwt8d3474vyadywrcn2sqj8m92e`

**Comment by ecurrencyhodler** [comment]
Just tried a tiny swap and it just confirmed!

**Comment by alexbosworth** [comment]
Awesome, thanks for the report that it wasn't working properly
