### ISSUE TITLE
Unexpected error :( try again or with a different invoice?

### ISSUE THREAD

**Issue by willcl-ark** [submarineswaps/swaps-service#104]
Do you know what causes this "unexpected error"? I have tried a number of testnet invoice, but all fail :(

lntb15u1pw3fe5rpp5mg3kkf76uehex6fjphavu3kp4xys98dhl3pwy8zdgujm3du206csdqqcqzpgvp3epxguwpztd8rgn7z0vssp3ce3252yp7y6wjxqh3th5lx30fvkxqc4ycgj3w30x36nj8m8cz8w4nj9t699z09t25jh4j58yulla6qpacc8xp

I have 3 channels open, one with Lightning Labs tesnet faucet, Acinq's 'endurance' and one other. Each has remote funds > 1% of channel capacity, so receive capability I believe, is not the issue.

If I generate an invoice from starblocks, it will be accepted, an invoice of the same value of mine will fail with this error.

I have tried generating a lot of new invoices (default settings, `lncli -n testnet addinvoice 1500` for example).

<img width="964" alt="image" src="https://user-images.githubusercontent.com/6606587/60281104-3501c600-98fc-11e9-9f8f-61fd69072265.png">

**Comment by alexbosworth** [comment]
Probably it tried to find a path to that destination and it couldn't

lnd changed up how route pathfinding works so this may be causing a problem, or there may really be no path
