### ISSUE TITLE
Funding not detected when paying to 'swap_p2wsh_address'

### ISSUE THREAD

**Issue by willcl-ark** [submarineswaps/swaps-service#105]
The `get_quote` api will return for example:

`{... trimmed ...
'swap_p2sh_address': '2N6BXXCqmmREN6r56X47S478ytbF7gvLSnA', 'swap_p2sh_p2wsh_address': '2N6FUDsH6d3ULwGyjXGoYXVVpkrAk2Lozca', 
'swap_p2wsh_address': 'tb1q88unzjwfqldn57e8u83yyz33zljw4yctsn3yfdpep9xnwh3p0ayq22t3sy', 'timeout_block_height': 1579502}`

Payment to either the `p2sh` or `p2sh_p2wsh` addresses will result in tx detection within a few seconds and continuation of the swap process, however paying to the native Segwit `p2wsh` address results in the funding never being detected.

**Comment by alexbosworth** [comment]
Should be working now

**Comment by willcl-ark** [comment]
Working it is!
