### ISSUE TITLE
Create construction for swap that uses hash160

### ISSUE THREAD

**Issue by alexbosworth** [submarineswaps/swaps-service#87]
Instead of using the SHA256 for the preimage check, check the preimage against a SHA256 + HASH160. When constructing the script perform ripemd-160 against the invoice payment hash.

**Comment by federicobond** [comment]
I believe this was fixed by https://github.com/submarineswaps/swaps-service/commit/fbc711019d0830b23e755233492cb8ad26b0b326.

**Comment by alexbosworth** [comment]
Yes this was fixed
